# Generated by Django 5.0.2 on 2024-03-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_unn', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('UG', 'UNDERGRADUATE'), ('PG', 'POSTGRADUATE'), ('SD', 'SANDWICH')], default='UG', max_length=2),
        ),
    ]
