# Generated by Django 5.0.2 on 2024-03-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('dept', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UG', 'UNDERGRADUATE'), ('PG', 'POSTGRADUATE'), ('SD', 'SANDWICH')], default='UG', max_length=2)),
            ],
        ),
    ]
