# Generated by Django 5.0.2 on 2024-03-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0002_lecturer_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='level',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='status',
            field=models.CharField(choices=[('LC', 'LECTURER'), ('DO', 'DOCTORATE'), ('PF', 'PROFESSOR')], default='LC', max_length=2),
        ),
    ]
